apiVersion: apps/v1
kind: Deployment
metadata:
  name: guy-projecthelmchart
spec:
  selector:
    matchLabels:
      app: guy-projecthelmchart
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: guy-projecthelmchart
    spec:
      containers:
      - name: guy-projecthelmchart
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.ports.port }}