apiVersion: v1
kind: Service
metadata:
  name: guy-projecthelmchart-service
spec:
  selector:
    app: guy-projecthelmchart
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
  type: {{ .Values.service.type }}